DROP TABLE IF EXISTS usuario CASCADE;
DROP TABLE IF EXISTS amizade CASCADE;
DROP TABLE IF EXISTS solicitacoes CASCADE;
DROP TABLE IF EXISTS postagem CASCADE;
DROP TABLE IF EXISTS comentario CASCADE;
DROP TABLE IF EXISTS curtida CASCADE;



CREATE TABLE usuario (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                         apelido VARCHAR(50),
                         nome_completo VARCHAR(255) NOT NULL,
                         email VARCHAR(255) NOT NULL,
                         data_nasimento DATE NOT NULL ,
                         senha VARCHAR(100) NOT NULL,
                         foto VARCHAR(512),
                         ativo BOOLEAN NOT NULL
);
ALTER TABLE usuario ADD CONSTRAINT pk_usuario PRIMARY KEY (id);
ALTER TABLE usuario ADD CONSTRAINT uk_usuario_email UNIQUE (email);

CREATE TABLE amizade (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                         usuario_id BIGINT NOT NULL,
                         amigo_id BIGINT NOT NULL

);
ALTER TABLE amizade ADD CONSTRAINT pk_amizade PRIMARY KEY (id);
ALTER TABLE amizade ADD CONSTRAINT uk_amizade UNIQUE (usuario_id, amigo_id);
ALTER TABLE amizade ADD CONSTRAINT fk_amizade_usuario FOREIGN KEY (usuario_id) REFERENCES usuario;
ALTER TABLE amizade ADD CONSTRAINT fk_amizade_amigo FOREIGN KEY (amigo_id) REFERENCES usuario;


CREATE TABLE solicitacoes (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                              usuario_id BIGINT NOT NULL,
                              usuario_solicitacao_id BIGINT NOT NULL

);
ALTER TABLE solicitacoes ADD CONSTRAINT pk_solicitacoes PRIMARY KEY (id);
ALTER TABLE solicitacoes ADD CONSTRAINT uk_solicitacoes UNIQUE (usuario_id, usuario_solicitacao_id);
ALTER TABLE solicitacoes ADD CONSTRAINT fk_solicitacoes_usuario FOREIGN KEY (usuario_id) REFERENCES usuario;
ALTER TABLE solicitacoes ADD CONSTRAINT fk_solicitacoes_amigo FOREIGN KEY (usuario_solicitacao_id) REFERENCES usuario;


CREATE TABLE postagem (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                          data_postagem TIMESTAMP NOT NULL ,
                          foto VARCHAR(512),
                          legenda VARCHAR(512),
                          privada BOOLEAN NOT NULL,
                          usuario_id BIGINT
);
ALTER TABLE postagem ADD CONSTRAINT pk_postagem PRIMARY KEY (id);
ALTER TABLE postagem ADD CONSTRAINT fk_postagem_usuario FOREIGN KEY (usuario_id) REFERENCES usuario;


CREATE TABLE comentario (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                            comentario VARCHAR(512) NOT NULL,
                            postagem_id BIGINT,
                            usuario_id BIGINT

);
ALTER TABLE comentario ADD CONSTRAINT pk_comentario PRIMARY KEY (id);
ALTER TABLE comentario ADD CONSTRAINT fk_comentario_usuario FOREIGN KEY (usuario_id) REFERENCES usuario;
ALTER TABLE comentario ADD CONSTRAINT fk_comentario_postagem FOREIGN KEY (postagem_id) REFERENCES postagem;


CREATE TABLE curtida (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                         postagem_id BIGINT,
                         usuario_id BIGINT

);
ALTER TABLE curtida ADD CONSTRAINT pk_curtida PRIMARY KEY (id);
ALTER TABLE curtida ADD CONSTRAINT uk_curtida_usuario_postagem UNIQUE (usuario_id, postagem_id);
ALTER TABLE curtida ADD CONSTRAINT fk_curtida_usuario FOREIGN KEY (usuario_id) REFERENCES usuario;
ALTER TABLE curtida ADD CONSTRAINT fk_curtida_postagem FOREIGN KEY (postagem_id) REFERENCES postagem;

