api:
  devolucao:
    dias: 5
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/racha
    username: postgres
    password: 8718
  jpa:
    hibernate:
       ddl-auto: validate
server:
  error:
    include-message: always

